apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: klqpibofj-go 
  janus-idp.io/tekton: klqpibofj-go
  backstage.io/kubernetes-id: klqpibofj-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: klqpibofj-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml